/**
 * Regenerate the "Data Coverage" table in README.md (#255).
 *
 * Source of truth:
 *   - public/data/<game>/data-version.json  → game_version, refreshed_at, coverage_notes (manual)
 *   - public/data/<game>/game-defs.json `dlc` → DLC counts (derived; one canonical home)
 *
 * The README never carries a hand-maintained DLC count — it's counted from the
 * `dlc` registry via dlcCoverageCounts(), the same function the UI footer uses,
 * so the two surfaces can't drift from each other or from the data.
 *
 * Run after every data refresh (and wire it into the refresh in #284):
 *   npx tsx scripts/gen-data-coverage.ts
 *
 * Edit the manual fields in public/data/<game>/data-version.json, then re-run
 * this to sync the README. Run with `--check` in CI to fail when the committed
 * README is stale instead of rewriting it.
 */
import { readFileSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { dlcCoverageCounts, type DlcSection, type DlcCoverageCounts } from '../src/frontend/dlc-data';
import type { DataVersion } from '../src/frontend/types';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const GAMES = [
  { id: 'ets2', label: 'ETS2' },
  { id: 'ats', label: 'ATS' },
] as const;

const BEGIN = '<!-- BEGIN data-coverage (generated by scripts/gen-data-coverage.ts — do not edit by hand) -->';
const END = '<!-- END data-coverage -->';

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, 'utf8')) as T;
}

function row(label: string, dv: DataVersion, c: DlcCoverageCounts): string {
  // coverage_notes is free-form human-authored text. Neutralize the two things
  // that corrupt a Markdown table cell: a literal pipe (splits the cell) and a
  // newline (splits the row). Escape the first, collapse the second to a space.
  const notes = (dv.coverage_notes.trim() || '—').replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ');
  return `| ${label} | ${dv.game_version} | ${dv.refreshed_at} | ${c.total} (${c.trailer} / ${c.cargo} / ${c.map}) | ${notes} |`;
}

function buildTable(): string {
  const rows = GAMES.map(({ id, label }) => {
    const dv = readJson<DataVersion>(resolve(ROOT, `public/data/${id}/data-version.json`));
    const defs = readJson<{ dlc: DlcSection }>(resolve(ROOT, `public/data/${id}/game-defs.json`));
    return row(label, dv, dlcCoverageCounts(defs.dlc));
  });
  return [
    BEGIN,
    '| Game | Version | Refreshed | DLCs (trailer / cargo / map) | Notes |',
    '|------|---------|-----------|------------------------------|-------|',
    ...rows,
    END,
  ].join('\n');
}

const table = buildTable();
const readmePath = resolve(ROOT, 'README.md');
const readme = readFileSync(readmePath, 'utf8');

const escaped = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const blockRe = new RegExp(`${escaped(BEGIN)}[\\s\\S]*?${escaped(END)}`);
if (!blockRe.test(readme)) {
  throw new Error('Data Coverage markers not found in README.md — add the BEGIN/END block first.');
}

const updated = readme.replace(blockRe, table);
const check = process.argv.includes('--check');
if (check) {
  if (updated !== readme) {
    console.error('README.md Data Coverage table is stale — run: npx tsx scripts/gen-data-coverage.ts');
    process.exit(1);
  }
  console.log('README.md Data Coverage table is up to date.');
} else {
  writeFileSync(readmePath, updated);
  console.log('README.md Data Coverage table regenerated.');
}
